#!/usr/bin/env bash
#
# miner.sh — interactive miner workflow for Swarm SN124 (Interceptor-first).
#
# Interactive menu (default when run with no args):
#   1) Install dependencies
#   2) Publish ./model to GitHub (validators pull this repo)
#   3) Download from GitHub and run local verify / benchmark
#   4) Test local ./model format only
#   5) Environment doctor
#   q) Quit
#
# Non-interactive (still supported):
#   ./miner.sh install | publish | pull-test | test | package | bench | doctor | selftest | menu
#
# Defaults target Interceptor, Python 3.10, and https://github.com/viasamonte74/drohunter
#
# Your agent lives in ./model (git-ignored). It must contain drone_agent.py at
# its root, plus any weights. Do NOT put main.py, agent.capnp or agent_server.py
# there — evaluation injects those.
#
# Configuration (env or flags):
#   SWARM_FAMILY_ID       --family <id>       [cf_interceptor]
#   SWARM_MODEL_DIR       --model-dir <d>     [model]
#   SWARM_GITHUB_URL      --github-url <url>  [https://github.com/viasamonte74/drohunter]
#   SWARM_PUBLISH_DIR     --publish-dir <d>   [publish/drohunter]
#   SWARM_DOWNLOAD_DIR    --download-dir <d>  [downloads/drohunter]
#   SWARM_PYTHON          --python <bin>      [python3.10]
#   SWARM_SEEDS           --seeds <n>         [1]
#   SWARM_WORKERS         --workers <n>
#   SWARM_SYSTEM_DEPS     --system            also run apt installer
#   SWARM_GIT_BRANCH      --branch <name>     [main]
#   SWARM_SKIP_PUSH=1                         package locally without git push
#
set -Eeuo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

FAMILY_ID="${SWARM_FAMILY_ID:-cf_interceptor}"
MODEL_DIR="${SWARM_MODEL_DIR:-model}"
PYTHON_BIN="${SWARM_PYTHON:-python3.10}"
SEEDS_PER_GROUP="${SWARM_SEEDS:-1}"
WORKERS="${SWARM_WORKERS:-}"
WANT_SYSTEM_DEPS="${SWARM_SYSTEM_DEPS:-0}"
GITHUB_URL="${SWARM_GITHUB_URL:-https://github.com/viasamonte74/drohunter}"
PUBLISH_DIR="${SWARM_PUBLISH_DIR:-publish/drohunter}"
DOWNLOAD_DIR="${SWARM_DOWNLOAD_DIR:-downloads/drohunter}"
GIT_BRANCH="${SWARM_GIT_BRANCH:-main}"
SKIP_PUSH="${SWARM_SKIP_PUSH:-0}"
SETTINGS_FILE="${SWARM_SETTINGS_FILE:-.swarm-miner.env}"

VENV_DIR="miner_env"
SUBMISSION_ZIP="Submission/submission.zip"
VALID_FAMILIES=(cf_autopilot cf_search_and_rescue cf_swarm_autopilot cf_swarm_sar cf_interceptor)

if [[ -t 1 ]]; then
  C_RED=$'\e[31m'; C_GRN=$'\e[32m'; C_YEL=$'\e[33m'; C_BLU=$'\e[34m'; C_OFF=$'\e[0m'
else
  C_RED=''; C_GRN=''; C_YEL=''; C_BLU=''; C_OFF=''
fi
info()  { printf '%s[INFO]%s %s\n'  "$C_BLU" "$C_OFF" "$*"; }
ok()    { printf '%s[OK]%s %s\n'    "$C_GRN" "$C_OFF" "$*"; }
warn()  { printf '%s[WARN]%s %s\n'  "$C_YEL" "$C_OFF" "$*" >&2; }
die()   { printf '%s[ERROR]%s %s\n' "$C_RED" "$C_OFF" "$*" >&2; exit 1; }
step()  { printf '\n%s══ %s%s\n' "$C_BLU" "$*" "$C_OFF"; }

# Interactive menu must not die on a failed read/choice; commands keep ERR trap.
_ERR_TRAP_CMD='die "failed at line $LINENO: ${BASH_COMMAND}"'
trap "$_ERR_TRAP_CMD" ERR

usage() {
  # Print leading comment block only (stop at first non-comment line).
  awk 'NR==1{next} /^#/{sub(/^# ?/,""); print; next} {exit}' "${BASH_SOURCE[0]}"
}

COMMANDS=()
WANT_MENU=0
while (($#)); do
  case "$1" in
    install|publish|pull-test|test|package|bench|benchmark|doctor|selftest|all|menu)
      COMMANDS+=("$1"); shift ;;
    --family)       FAMILY_ID="${2:?}"; shift 2 ;;
    --model-dir)    MODEL_DIR="${2:?}"; shift 2 ;;
    --github-url)   GITHUB_URL="${2:?}"; shift 2 ;;
    --publish-dir)  PUBLISH_DIR="${2:?}"; shift 2 ;;
    --download-dir) DOWNLOAD_DIR="${2:?}"; shift 2 ;;
    --python)       PYTHON_BIN="${2:?}"; shift 2 ;;
    --seeds)        SEEDS_PER_GROUP="${2:?}"; shift 2 ;;
    --workers)      WORKERS="${2:?}"; shift 2 ;;
    --branch)       GIT_BRANCH="${2:?}"; shift 2 ;;
    --system)       WANT_SYSTEM_DEPS=1; shift ;;
    --skip-push)    SKIP_PUSH=1; shift ;;
    -h|--help)      usage; exit 0 ;;
    *)              die "unknown argument: $1  (try --help)" ;;
  esac
done
if ((${#COMMANDS[@]} == 0)); then
  WANT_MENU=1
fi

validate_family() {
  local candidate
  for candidate in "${VALID_FAMILIES[@]}"; do
    [[ "$FAMILY_ID" == "$candidate" ]] && return 0
  done
  die "unknown family '$FAMILY_ID'. Valid: ${VALID_FAMILIES[*]}"
}

normalize_github_url() {
  local raw="${1%/}"
  raw="${raw%.git}"
  if [[ ! "$raw" =~ ^https://github.com/[^/]+/[^/]+$ ]]; then
    die "GitHub URL must be exactly https://github.com/OWNER/REPO (got: $1)"
  fi
  echo "$raw"
}

github_owner_repo() {
  local url
  url="$(normalize_github_url "$1")"
  echo "${url#https://github.com/}"
}

write_settings() {
  local url
  url="$(normalize_github_url "$GITHUB_URL")"
  cat > "$SETTINGS_FILE" <<EOF
# Generated by miner.sh — settings validators / on-chain commit use.
SWARM_FAMILY_ID=$FAMILY_ID
SWARM_GITHUB_URL=$url
SWARM_MODEL_DIR=$MODEL_DIR
SWARM_GIT_BRANCH=$GIT_BRANCH
SWARM_PUBLISH_DIR=$PUBLISH_DIR
SWARM_DOWNLOAD_DIR=$DOWNLOAD_DIR
EOF
  ok "Wrote miner settings: $SETTINGS_FILE"
  info "On-chain commit example (after the repo is public and verified):"
  printf '  source %s/bin/activate\n' "$VENV_DIR"
  printf '  python neurons/miner.py --netuid 124 \\\n'
  printf '    --wallet.name YOUR_COLDKEY --wallet.hotkey YOUR_HOTKEY \\\n'
  printf '    --github_url %s\n' "$url"
}

activate_venv() {
  [[ -f "$VENV_DIR/bin/activate" ]] \
    || die "no venv at ./$VENV_DIR — choose menu option 1 (install) first"
  # shellcheck disable=SC1091
  source "$VENV_DIR/bin/activate"
  command -v swarm >/dev/null 2>&1 \
    || die "the 'swarm' CLI is not in the venv — re-run install"
}

resolve_python() {
  # Prefer the explicit binary (default: python3.10). Accept python3 only when
  # it is already 3.10.x so a host default of 3.12 cannot silently win.
  if command -v "$PYTHON_BIN" >/dev/null 2>&1; then
    local resolved_ver
    resolved_ver="$("$PYTHON_BIN" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
    case "$resolved_ver" in
      3.10) echo "$PYTHON_BIN"; return 0 ;;
      *)
        warn "$PYTHON_BIN is $resolved_ver — this miner workflow expects Python 3.10"
        ;;
    esac
  fi
  if command -v python3.10 >/dev/null 2>&1; then
    echo "python3.10"; return 0
  fi
  local version
  if command -v python3 >/dev/null 2>&1; then
    version="$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
    case "$version" in
      3.10) echo "python3"; return 0 ;;
    esac
  fi
  return 1
}

ensure_model_dir() {
  if [[ ! -d "$MODEL_DIR" ]]; then
    warn "No ./$MODEL_DIR — scaffolding Interceptor starter from submission template"
    mkdir -p "$MODEL_DIR"
    cp swarm/submission_template/drone_agent.py "$MODEL_DIR/drone_agent.py"
    ok "Created ./$MODEL_DIR/drone_agent.py — replace with your Interceptor policy + weights"
  fi
  [[ -f "$MODEL_DIR/drone_agent.py" ]] \
    || die "./$MODEL_DIR/drone_agent.py is missing (must sit at the folder root)"

  local found_forbidden=0 entry
  while IFS= read -r entry; do
    [[ -z "$entry" ]] && continue
    if (( found_forbidden == 0 )); then
      warn "These file types are rejected at intake and must be removed:"
      found_forbidden=1
    fi
    printf '  %s\n' "$entry" >&2
  done < <(find "$MODEL_DIR" -type f \( -name '*.exe' -o -name '*.so' -o -name '*.dll' \
    -o -name '*.sh' -o -name '*.bat' -o -name '*.pyc' \
    -o -name 'main.py' -o -name 'agent.capnp' -o -name 'agent_server.py' \) \
    -printf '%P\n' 2>/dev/null || true)
  (( found_forbidden == 0 )) || die "Remove forbidden files from ./$MODEL_DIR before continuing"

  if find "$MODEL_DIR" -type l -print -quit | grep -q .; then
    die "Symlinks inside the model folder are rejected at intake"
  fi
  local size_mib
  size_mib="$(du -sm "$MODEL_DIR" | cut -f1)"
  info "Model folder: ./$MODEL_DIR (${size_mib} MiB uncompressed; intake limit is 50 MiB)"
  if (( size_mib > 50 )); then
    die "Over the 50 MiB uncompressed limit"
  fi
}

ensure_git_repo_checkout() {
  # Clone or update a working tree used for packaging / pull-test.
  local dest="$1"
  local url
  url="$(normalize_github_url "$GITHUB_URL")"
  mkdir -p "$(dirname "$dest")"
  if [[ -d "$dest/.git" ]]; then
    info "Updating existing checkout $dest"
    git -C "$dest" remote set-url origin "$url"
    # Prefer requested branch; fall back to master if main is absent.
    if git -C "$dest" fetch origin "$GIT_BRANCH" 2>/dev/null; then
      git -C "$dest" checkout "$GIT_BRANCH" 2>/dev/null \
        || git -C "$dest" checkout -B "$GIT_BRANCH" "origin/$GIT_BRANCH"
      git -C "$dest" pull --ff-only origin "$GIT_BRANCH" || true
    elif git -C "$dest" fetch origin master 2>/dev/null; then
      warn "Branch '$GIT_BRANCH' missing; using master"
      GIT_BRANCH=master
      git -C "$dest" checkout master 2>/dev/null || true
      git -C "$dest" pull --ff-only origin master || true
    else
      warn "Could not fetch remote yet (empty repo is OK for first publish)"
    fi
  else
    info "Cloning $url -> $dest"
    if ! git clone --branch "$GIT_BRANCH" "$url" "$dest" 2>/dev/null; then
      if ! git clone --branch master "$url" "$dest" 2>/dev/null; then
        info "Remote empty or unreachable — initializing local publish repo"
        mkdir -p "$dest"
        git -C "$dest" init
        git -C "$dest" checkout -B "$GIT_BRANCH"
        git -C "$dest" remote add origin "$url" 2>/dev/null \
          || git -C "$dest" remote set-url origin "$url"
      else
        GIT_BRANCH=master
      fi
    fi
  fi
}

# ── commands ─────────────────────────────────────────────────────────────────
cmd_install() {
  step "Installing dependencies"

  if [[ "$WANT_SYSTEM_DEPS" == "1" ]]; then
    info "Running scripts/miner/install_dependencies.sh (sudo, apt upgrade)"
    local codename
    codename="$(lsb_release -cs 2>/dev/null || echo unknown)"
    case "$codename" in
      jammy|noble) ;;
      *) warn "Ubuntu '$codename' is outside jammy/noble — python3.10 may need manual install" ;;
    esac
    chmod +x scripts/miner/install_dependencies.sh
    ./scripts/miner/install_dependencies.sh
  else
    info "Skipping system packages (re-run with --system for apt installer)"
  fi

  local python_exe
  python_exe="$(resolve_python)" || die \
    "Need Python 3.10. Install it, then re-run option 1.
       Example:
         sudo add-apt-repository ppa:deadsnakes/ppa -y && sudo apt update
         sudo apt install -y python3.10 python3.10-venv python3.10-dev
       Or point at it:  ./miner.sh install --python /usr/bin/python3.10"
  info "Using interpreter: $python_exe ($("$python_exe" --version 2>&1))"

  if [[ -d "$VENV_DIR" ]]; then
    # Recreate the venv when it was built with a different major.minor so an
    # old 3.12 miner_env cannot keep being reused after switching to 3.10.
    local venv_ver=""
    if [[ -x "$VENV_DIR/bin/python" ]]; then
      venv_ver="$("$VENV_DIR/bin/python" -c 'import sys; print("%d.%d" % sys.version_info[:2])' 2>/dev/null || true)"
    fi
    if [[ "$venv_ver" != "3.10" ]]; then
      warn "Existing ./$VENV_DIR uses Python ${venv_ver:-unknown} — recreating with 3.10"
      rm -rf "$VENV_DIR"
    fi
  fi

  if [[ ! -d "$VENV_DIR" ]]; then
    info "Creating virtualenv ./$VENV_DIR"
    "$python_exe" -m venv "$VENV_DIR"
  else
    info "Reusing existing virtualenv ./$VENV_DIR"
  fi
  # shellcheck disable=SC1091
  source "$VENV_DIR/bin/activate"

  info "Upgrading pip and setuptools"
  python -m pip install --upgrade pip setuptools >/dev/null

  info "Installing pinned requirements (torch + bittensor — slow)"
  pip install -r requirements.txt

  info "Installing this package in editable mode"
  pip install -e . --no-deps

  python -c 'import bittensor; print("bittensor", bittensor.__version__)' \
    || warn "bittensor imported with errors — check the install log above"
  write_settings
  ok "Dependencies installed. Activate with: source $VENV_DIR/bin/activate"
}

cmd_doctor() {
  step "Environment readiness (swarm doctor)"
  activate_venv
  if swarm doctor; then
    ok "All required checks passed"
  else
    warn "Some required checks failed — format 'test' still works; Docker bench may not"
  fi
}

cmd_test() {
  validate_family
  step "Validating ./$MODEL_DIR for family $FAMILY_ID"
  activate_venv
  ensure_model_dir
  swarm model test --source "$MODEL_DIR" --family-id "$FAMILY_ID"
  ok "Model folder passes format / packaging checks"
}

cmd_package() {
  validate_family
  step "Packaging ./$MODEL_DIR -> $SUBMISSION_ZIP"
  activate_venv
  ensure_model_dir
  mkdir -p "$(dirname "$SUBMISSION_ZIP")"
  swarm model package --source "$MODEL_DIR" --family-id "$FAMILY_ID" \
    --output "$SUBMISSION_ZIP" --overwrite
  swarm model verify --model "$SUBMISSION_ZIP"
  ok "Built and verified $SUBMISSION_ZIP"
}

cmd_publish() {
  # Package interceptor artifact into the GitHub submission repo and push.
  validate_family
  local url
  url="$(normalize_github_url "$GITHUB_URL")"
  step "Publish ./$MODEL_DIR → $url  (family $FAMILY_ID)"
  activate_venv
  ensure_model_dir

  info "Pre-flight: local model test"
  swarm model test --source "$MODEL_DIR" --family-id "$FAMILY_ID"

  ensure_git_repo_checkout "$PUBLISH_DIR"

  info "Building repo layout (manifest + artifacts/$FAMILY_ID/submission.zip + template README)"
  swarm repo package \
    --repo-root "$PUBLISH_DIR" \
    --family-source "${FAMILY_ID}=${MODEL_DIR}" \
    --overwrite

  info "Verifying repo layout (strict)"
  swarm repo verify --repo-root "$PUBLISH_DIR" --strict-manifest

  write_settings

  if [[ "$SKIP_PUSH" == "1" ]]; then
    warn "SWARM_SKIP_PUSH=1 — skipped git commit/push"
    ok "Packaged at $PUBLISH_DIR (push manually when ready)"
    return 0
  fi

  command -v git >/dev/null 2>&1 || die "git is required to publish"
  (
    cd "$PUBLISH_DIR"
    git add README.md submission_manifest.json artifacts/
    if git diff --cached --quiet; then
      warn "Nothing new to commit (artifact unchanged?)"
    else
      git commit -m "Publish ${FAMILY_ID} submission for Swarm SN124"
    fi
    # Ensure upstream exists.
    if ! git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
      info "Setting upstream origin/$GIT_BRANCH"
      git push -u origin "HEAD:${GIT_BRANCH}"
    else
      git push origin "HEAD:${GIT_BRANCH}"
    fi
  )
  ok "Published to $url (branch $GIT_BRANCH)"
  info "Validators fetch: $url  (public repo, main/master, submission_manifest.json)"
  info "Do NOT edit README.md by hand — swarm repo package owns its SHA-256"
}

cmd_pull_test() {
  validate_family
  local url artifact
  url="$(normalize_github_url "$GITHUB_URL")"
  step "Download $url and local-test family $FAMILY_ID"
  activate_venv

  ensure_git_repo_checkout "$DOWNLOAD_DIR"

  [[ -f "$DOWNLOAD_DIR/submission_manifest.json" ]] \
    || die "No submission_manifest.json in $DOWNLOAD_DIR — publish first (menu option 2)"

  info "Verifying downloaded repo layout"
  swarm repo verify --repo-root "$DOWNLOAD_DIR" --strict-manifest

  artifact="$DOWNLOAD_DIR/artifacts/$FAMILY_ID/submission.zip"
  [[ -f "$artifact" ]] || die "Missing $artifact — repo is not packaged for $FAMILY_ID"

  info "Verifying artifact zip"
  swarm model verify --model "$artifact"

  command -v docker >/dev/null 2>&1 \
    || die "docker is required for the local benchmark"
  docker info >/dev/null 2>&1 \
    || die "docker daemon not reachable (try: sudo systemctl start docker)"

  local -a bench_args=(--model "$artifact" --family-id "$FAMILY_ID"
                       --seeds-per-group "$SEEDS_PER_GROUP")
  [[ -n "$WORKERS" ]] && bench_args+=(--workers "$WORKERS")
  info "swarm benchmark ${bench_args[*]}"
  swarm benchmark "${bench_args[@]}"
  ok "Pull-test finished for $url (log: /tmp/bench_full_eval.log)"
}

cmd_bench() {
  validate_family
  step "Local benchmark ($FAMILY_ID, $SEEDS_PER_GROUP seed(s) per map group)"
  activate_venv
  command -v docker >/dev/null 2>&1 || die "docker is required for the benchmark sandbox"
  docker info >/dev/null 2>&1 || die "docker daemon is not reachable"
  [[ -f "$SUBMISSION_ZIP" ]] || cmd_package
  local -a bench_args=(--model "$SUBMISSION_ZIP" --family-id "$FAMILY_ID"
                       --seeds-per-group "$SEEDS_PER_GROUP")
  [[ -n "$WORKERS" ]] && bench_args+=(--workers "$WORKERS")
  swarm benchmark "${bench_args[@]}"
  ok "Benchmark finished (full log: /tmp/bench_full_eval.log)"
}

cmd_selftest() {
  step "Repo test suite (pytest)"
  activate_venv
  pytest -q -m "not slow and not integration"
  ok "Repo test suite passed"
}

cmd_all() { cmd_install; cmd_doctor; cmd_test; cmd_publish; }

show_menu() {
  local url
  url="$(normalize_github_url "$GITHUB_URL")"
  printf '\n'
  printf '%s╔══════════════════════════════════════════════════════════╗%s\n' "$C_BLU" "$C_OFF"
  printf '%s║%s  Swarm SN124 miner — Interceptor workflow               %s║%s\n' "$C_BLU" "$C_OFF" "$C_BLU" "$C_OFF"
  printf '%s╚══════════════════════════════════════════════════════════╝%s\n' "$C_BLU" "$C_OFF"
  printf '  Family : %s\n' "$FAMILY_ID"
  printf '  Model  : ./%s\n' "$MODEL_DIR"
  printf '  GitHub : %s\n' "$url"
  printf '  Branch : %s\n' "$GIT_BRANCH"
  printf '\n'
  printf '  %s1%s) Install dependencies\n' "$C_GRN" "$C_OFF"
  printf '  %s2%s) Publish ./model to GitHub (validators use this repo)\n' "$C_GRN" "$C_OFF"
  printf '  %s3%s) Download from GitHub + local verify/benchmark\n' "$C_GRN" "$C_OFF"
  printf '  %s4%s) Test local ./model format only\n' "$C_GRN" "$C_OFF"
  printf '  %s5%s) Environment doctor\n' "$C_GRN" "$C_OFF"
  printf '  %sq%s) Quit\n' "$C_YEL" "$C_OFF"
  printf '\n'
}

interactive_menu() {
  # Disable hard ERR trap around the prompt so Cancel/empty input is safe.
  trap - ERR
  local choice
  while true; do
    show_menu
    printf 'Select [1-5 / q]: '
    IFS= read -r choice || true
    choice="$(echo "$choice" | tr -d '[:space:]')"
    case "$choice" in
      1)
        trap "$_ERR_TRAP_CMD" ERR
        cmd_install
        trap - ERR
        ;;
      2)
        trap "$_ERR_TRAP_CMD" ERR
        cmd_publish
        trap - ERR
        ;;
      3)
        trap "$_ERR_TRAP_CMD" ERR
        cmd_pull_test
        trap - ERR
        ;;
      4)
        trap "$_ERR_TRAP_CMD" ERR
        cmd_test
        trap - ERR
        ;;
      5)
        trap "$_ERR_TRAP_CMD" ERR
        cmd_doctor
        trap - ERR
        ;;
      q|Q|0|quit|Quit|"")
        ok "Bye"
        exit 0
        ;;
      *)
        warn "Unknown choice: $choice"
        ;;
    esac
  done
}

run_command() {
  case "$1" in
    install)         cmd_install ;;
    publish)         cmd_publish ;;
    pull-test)       cmd_pull_test ;;
    doctor)          cmd_doctor ;;
    test)            cmd_test ;;
    package)         cmd_package ;;
    bench|benchmark) cmd_bench ;;
    selftest)        cmd_selftest ;;
    all)             cmd_all ;;
    menu)            interactive_menu ;;
    *)               die "unknown command: $1" ;;
  esac
}

# ── run ──────────────────────────────────────────────────────────────────────
if (( WANT_MENU == 1 )); then
  interactive_menu
else
  for command in "${COMMANDS[@]}"; do
    run_command "$command"
  done
  printf '\n'
  ok "Done: ${COMMANDS[*]}"
fi
