"""Shared imports, constants, and caches for warehouse helpers."""

import json
import math
import os
import random
import shutil

import pybullet as p

from swarm.core.warehouse.constants import (
    CONVEYOR_ASSETS,
    CONVEYOR_KIT_OBJ_DIR,
    CONVEYOR_KIT_TEXTURE,
    ENABLE_FORKLIFT_PARKING,
    ENABLE_LOADING_OPERATION_FORKLIFTS,
    ENABLE_LOADING_STAGING,
    ENABLE_LOADING_TRUCKS,
    ENABLE_MACHINING_CELL_LAYOUT,
    ENABLE_STORAGE_RACK_LAYOUT,
    FLOOR_INNER_MARGIN_TILES,
    FLOOR_SPAWN_SAFETY_MARGIN_M,
    FORKLIFT_MODEL_NAME,
    FORKLIFT_TEXTURE_NAME,
    HALF_X,
    HALF_Y,
    LOADING_KIT_DIR,
    LOADING_STAGING_MODELS,
    LOADING_TRUCK_EXTRA_GAP_CLOSED,
    LOADING_TRUCK_EXTRA_GAP_HALF,
    LOADING_TRUCK_MODELS,
    LOADING_TRUCK_SCALE_XYZ,
    MACHINING_FORCE_REFRESH_MTL_PROXY,
    STORAGE_RACK_MODEL_NAME,
    UNIFORM_SCALE,
    UNIFORM_SPECULAR_COLOR,
    VEHICLE_DIR,
    WAREHOUSE_BASE_SIZE_X,
    WAREHOUSE_BASE_SIZE_Y,
    WAREHOUSE_SHELL_DIR,
    WAREHOUSE_SHELL_FILES,
    WAREHOUSE_SIZE_X,
    WAREHOUSE_SIZE_Y,
)
from swarm.core.warehouse.shared import normalize_mtl_texture_paths

_TEXTURE_CACHE = {}
_OBJ_MTL_SPLIT_CACHE = {}
_OBJ_COLLISION_PROXY_CACHE = {}
_OBJ_MTL_VISUAL_PROXY_CACHE = {}
_OBJ_DOUBLE_SIDED_PROXY_CACHE = {}
_LOADING_TRUCK_ALONG_EXTENT_CACHE = {}
_NORMALIZED_MTL_DIRS = set()
_MESH_VISUAL_SHAPE_CACHE = {}
_MESH_COLLISION_SHAPE_CACHE = {}
_RESOLVED_MESH_PATH_CACHE = {}
_ORIENTED_XY_SIZE_CACHE = {}
_MODEL_BOUNDS_CACHE = {}

__all__ = [name for name in globals() if not name.startswith('__')]
