"""Render per-family model I/O tables from the domain schema.

The blocks land in docs/families/<family>.md between io-tables markers, so the
tables always match swarm/domain_model/benchmark_domain_model.schema.json.

    python3 scripts/gen_family_io_tables.py            # print all blocks
    python3 scripts/gen_family_io_tables.py --write    # update the docs in place
    python3 scripts/gen_family_io_tables.py --check    # exit 1 if any doc drifted
"""
import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO / "swarm" / "domain_model" / "benchmark_domain_model.schema.json"
DOCS_DIR = REPO / "docs" / "families"
BEGIN = "<!-- io-tables:begin (generated by scripts/gen_family_io_tables.py, do not edit by hand) -->"
END = "<!-- io-tables:end -->"


def _fmt(value) -> str:
    if isinstance(value, float) and value == int(value):
        return str(int(value))
    return str(value)


def _shape(value) -> str:
    return "(" + ", ".join(str(v) for v in value) + ")"


def render_block(schema: dict, family_id: str) -> str:
    interface = schema["policy_interfaces"][f"{family_id}:submission_zip.v1"]
    family = schema["challenge_families"][family_id]
    obs = interface["observation_space"]
    action = interface["action_space"]
    smoke = interface.get("smoke_test_observation", {})

    lines = [BEGIN, ""]
    lines += [
        "### Model contract",
        "",
        "| | |",
        "|---|---|",
        f"| Interface version | `{interface['interface_version']}` |",
        f"| Entry point | `{interface['entry_point']['module']}.{interface['entry_point']['class_name']}` |",
        f"| Contract file | `{interface['contract_filename']}` ({interface['contract_version']}) |",
        f"| Environment types | {', '.join(family['environment_types'])} |",
        "",
        f"### Observation: `{obs['type']}` with keys {', '.join('`' + k + '`' for k in obs['required_keys'])}",
        "",
        "| Key | Dtype | Shape | Range / layout |",
        "|---|---|---|---|",
    ]
    for key, field in obs["fields"].items():
        if "minimum" in field and "maximum" in field:
            detail = f"[{_fmt(field['minimum'])}, {_fmt(field['maximum'])}]"
        else:
            channels = field.get("semantic_channels", [])
            detail = " → ".join(f"`{c}`" for c in channels) or "—"
        shape = _shape(field["shape"])
        if key in smoke and field["shape"] == ["dynamic"]:
            shape = f"{_shape(smoke[key]['shape'])} at evaluation settings"
        lines.append(f"| `{key}` | {field['dtype']} | {shape} | {detail} |")
    lines += [
        "",
        f"### Action: {action['dtype']} tensor, shape {_shape(action['shape'])}",
        "",
        "| # | Component | Min | Max |",
        "|---|---|---|---|",
    ]
    for i, name in enumerate(action["component_names"]):
        lines.append(
            f"| {i} | `{name}` | {_fmt(action['lower_bound'][i])} | {_fmt(action['upper_bound'][i])} |"
        )
    lines += ["", END]
    return "\n".join(lines)


def doc_path(family_id: str) -> Path:
    return DOCS_DIR / f"{family_id.removeprefix('cf_')}.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="update docs in place")
    mode.add_argument("--check", action="store_true", help="fail if docs drifted")
    args = parser.parse_args()

    schema = json.loads(SCHEMA_PATH.read_text())
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    failures = []
    for key in schema["policy_interfaces"]:
        family_id = key.split(":")[0]
        block = render_block(schema, family_id)
        path = doc_path(family_id)
        if not (args.write or args.check):
            print(f"\n{'=' * 30} {path.relative_to(REPO)}\n{block}")
            continue
        if not path.exists():
            failures.append(f"{path.relative_to(REPO)}: missing")
            continue
        text = path.read_text()
        if not pattern.search(text):
            failures.append(f"{path.relative_to(REPO)}: no io-tables markers")
            continue
        updated = pattern.sub(lambda _: block, text)
        if args.write and updated != text:
            path.write_text(updated)
            print(f"updated {path.relative_to(REPO)}")
        elif args.check and updated != text:
            failures.append(f"{path.relative_to(REPO)}: stale io-tables block")
    for failure in failures:
        print(failure, file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
